# Esta incompleto - puede fallar

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_HOST=http://localhost:5000
      - VITE_GEOSERVER=/geoserver/remap/wms?
    networks:
      - cle_network

  backend:
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
      args:
      - PORT=5000
    restart: unless-stopped

    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - GEOSERVER_URL=http://host.docker.internal:8080/geoserver
      - EHILUCS_HOST=http://localhost:3030/
      - USERNAME_GEOSERVER=admin
      - PASS_GEOSERVER=geoserver
    networks:
      - cle_network

networks:
  cle_network:
    driver: bridge
volumes:
  node_modules:
